-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: /var/www/wiki/mediawiki/extensions/LdapAuthentication/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/ldap_domains (
  domain_id INTEGER NOT NULL,
  domain VARCHAR(255) NOT NULL,
  user_id INTEGER NOT NULL,
  PRIMARY KEY(domain_id)
);

CREATE INDEX user_id ON /*_*/ldap_domains (user_id);
